version: "3"

services:
  server:
    image: minichat-plus:latest
    container_name: minichat-plus
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - "./config.yaml:/app/config.yaml"
    environment:
      - TEMPLATE_NAME=bulma
